.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DAPTUP 8 "Aug 15, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
daptup \- wrapper script on 'aptitude update'
.SH SYNOPSIS
.B daptup [-h | --help | --nocolor]
.br
.SH OPTIONS
.br
.TP
.B -h --help
prints the help
.TP
.B --nocolor
disables color output, useful for scripts or when output is not terminal
.PP
\fBdaptup\fP is a script that run "aptitude update" command inside and outputs list of packages recently entered to repo, list of packages which got new updates, list of changes in 'watched' packages and, optionally, list of outdated packages.
.SH FILES
.TP
.B /etc/daptup.conf
self-documented configuration file
.TP
.B /var/spool/daptup/outdated
cached file with info about outdated packages
.SH SEE ALSO
.BR aptitude (8),
.br
.SH AUTHOR
daptup was written by Eugene V. Lyubimkin.
.PP
This manual page was written by Eugene V. Lyubimkin <jackyf.devel@gmail.com>,
for the Debian project (but may be used by others).
