.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DAPTUP 8 "Oct 13, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
daptup \- wrapper script on 'aptitude update' or 'apt-get update'
.SH SYNOPSIS
.B daptup
[ \fB--pre\fP | \fB--post\fP | \fB--last\fP ]
[ \fB-h\fP | \fB--help\fP ] [ \fB--nocolor\fP ]
.br
.SH OPTIONS
.TP
.B --pre
Do only 'pre' stage: collect info that will be used as 'old'. Usually need to be specified only in apt hooks.
.TP
.B --post
If appropriate option is enabled in config file, do only 'post' stage: collect 'new' info and output changes. Otherwise do nothing. Usually need to be specified only in apt hooks.
.TP
.B --last
Output changes only. This option is supposed to be specified when you want to see changes made in the last update. Note that list of outdated packages, if daptup is configured to output it, will be rebuilt.
.TP
.B -h --help
prints the help
.TP
.B --nocolor
disables color output, useful for scripts or when output is not terminal
.PP
\fBdaptup\fP is a script that runs "aptitude update" if aptitude is installed or "apt-get update" otherwise inside and outputs list of packages recently entered to repo, list of packages which got new updates, list of changes in 'watched' packages and, optionally, list of outdated packages.
.PP
Starting with 0.8.0 version, \fBdaptup\fP uses apt hooks and you don't need to explicitly call it if you use 'apt-get update'.
.SH FILES
.TP
.B /etc/daptup.conf
self-documented configuration file
.TP
.B /var/spool/daptup/outdated
cached file with info about outdated packages
.SH SEE ALSO
.BR apt-get (8),
.BR aptitude (8),
.BR apt-show-versions (1p)
.SH AUTHOR
daptup was written by Eugene V. Lyubimkin.
.PP
This manual page was written by Eugene V. Lyubimkin <jackyf.devel@gmail.com>,
for the Debian project (but may be used by others).
